Unquote csv strings
motis-project/utl pull request #18
Opened 2024-04-29 15:54 UTC by jbruechert

2024-04-29 16:00 UTC, jbruechert commented
meh, the one case that wasn't easy to solve is the relevant one for MOTIS :(

EDIT: This may also not be the right place to do this

2024-04-29 16:10 UTC, felixguendling commented
`parse_arg` is still quite generic and also used in the HAFAS Rohdaten parser. Since the double quote escaping seems to be CSV specific, it could make sense to have it in a separate function that's only used by the CSV parser.

Maybe something overloading like this:

- `parse_csv(cstr s, std::string& t) { /* escape */ }`
- `parse_csv(cstr s, T& t) { parse_arg(cstr, t); }`

General note:
- I try to use [AAA style](https://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/) everywhere. I didn't do it since the beginning, so you'll find plenty of places where it's not AAA style. However, for new code it makes sense to stick to it.
- I would recommend to configure a "format on save" to have code formatted in the project specific way by default (no action required). Otherwise a commit hook or manual check before committing helps.
- In general the parser code should avoid temporary and unnecessary allocations at all costs to stay fast. Your code looks fine for now though. :+1:

2024-04-29 16:16 UTC, felixguendling commented
> meh, the one case that wasn't easy to solve is the relevant one for MOTIS :(
> 
> EDIT: This may also not be the right place to do this

I guess the way you started it here would require to change row types in these structs to `std::string`:
https://github.com/motis-project/nigiri/blob/55dde0d22013150f7db98054f336555c5003a781/src/loader/gtfs/stop.cc#L178-L179

In this case, it makes sense to `std::move` the string into the struct `stop` struct (or in other places the `trip` struct, etc.) to prevent allocating and copying more memory than necessary.

2024-04-29 16:20 UTC, felixguendling commented on include/utl/parser/arg_parser.h
> +    if (arg[found_at] == '"' && found_at < int(arg.size()) - 1) {
If possible (here it is) replace C-style casts with the more specific C++ versions (here: static_cast`).

Maybe the loop would be more readable with `while ((found_at = arg.find('"')) != -1) { ... }`.

2024-04-29 16:45 UTC, jbruechert commented
> I guess the way you started it here would require to change row types in these structs to `std::string`: https://github.com/motis-project/nigiri/blob/55dde0d22013150f7db98054f336555c5003a781/src/loader/gtfs/stop.cc#L178-L179
> 
> In this case, it makes sense to `std::move` the string into the struct `stop` struct (or in other places the `trip` struct, etc.) to prevent allocating and copying more memory than necessary.

Do you think that is a good way to go? I'm a bit unhappy about the inconsistency of the overloads between cstr and std::string.

2024-04-29 16:53 UTC, felixguendling commented
The question is: what is the alternative? To apply the unescaping function manually where necessary? But then where is it no necessary? Even for `agency_id`, etc. it's probably required if we do it correctly.

I think it's still good to have an escape hatch to prevent unescaping if you use `cstr` instead of `std::string`. The only problem I see is that it's not really obvious that one will be escaped and the other one not.

I think as long as there are no extra allocations, I am fine. I am a bit crazy with this.. especially temporary allocations :exploding_head:

2024-04-29 17:32 UTC, jbruechert commented
Makes sense.

Now for some reason I can't get the std::string overload to be called from stop.cc, I just hope the cause are not implicit conversions to cstr, since code depends on them all over the place.

EDIT: Okay no, I just got the wrong stop.cc and didn't notice.

2024-04-29 18:56 UTC, jbruechert commented
works now :+1:

2024-04-30 07:06 UTC, felixguendling requested changes
please run the formatter after these changes - then I think we're good to go :+1:

2024-04-30 07:06 UTC, felixguendling commented on include/utl/parser/csv.h
> +}
```suggestion
}

```

2024-04-30 07:06 UTC, felixguendling commented on include/utl/parser/csv.h
> +inline void unescape_quoted_string(std::string &arg) {
```suggestion
inline void unescape_quoted_string(std::string& arg) {
```

2024-04-30 07:06 UTC, felixguendling commented on include/utl/parser/csv.h
> +      found_at++; // Skip following character
```suggestion
      ++found_at; // Skip following character
```

2024-04-30 07:06 UTC, felixguendling commented on include/utl/parser/csv.h
> +      found_at++; // Skip following character
If both options do the same, `++i` is always preferable as it doesn't create a temporary. In `Release` mode it probably doesn't matter.

2024-04-30 07:06 UTC, felixguendling commented on include/utl/parser/csv.h
> +inline void parse_value(cstr& s, std::string& arg) {
```suggestion

inline void parse_value(cstr& s, std::string& arg) {
```

2024-04-30 07:13 UTC, felixguendling commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
`arg[found_at] == '"'` isn't this always true as the loop condition calls `found_at = arg.find('"')`?
The code replaces double quotes with single quotes, correct?
If that's true: why not use [`std::replace`](https://en.cppreference.com/w/cpp/algorithm/replace)?

2024-04-30 09:44 UTC, jbruechert commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
I don't think std::replace handle multi-element replacements.

the loop condition is missing a + 1, I'll fix it.

2024-04-30 09:48 UTC, jbruechert commented on include/utl/parser/csv.h
> +inline void parse_value(cstr& s, std::string& arg) {
This isn't new code, and the missing newlines are the same on the whole block of overloads.

2024-04-30 09:49 UTC, jbruechert commented on include/utl/parser/csv.h
> +inline void unescape_quoted_string(std::string &arg) {
I've now set up clang-format in QtCreator :)

2024-04-30 09:49 UTC, felixguendling commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
Ah, right. Then maybe it's a `boost::replace_all`? Or does this solution have better performance?

2024-04-30 10:28 UTC, jbruechert commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
I haven't really benchmarked it.
Coming from the Qt world I don't know too well what's available in boost, will try replace_all.

2024-04-30 10:39 UTC, jbruechert commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
boost::replace_all seems to be based around a dequeue and probably allocates memory. Maybe my function could actually be faster.

2024-04-30 11:52 UTC, felixguendling commented on include/utl/parser/csv.h
> +    if (arg[found_at] == '"' && found_at < static_cast<int>(arg.size()) - 1) {
Ok, then let's stick to your version.

2024-04-30 13:34 UTC, felixguendling requested changes

2024-04-30 13:34 UTC, felixguendling commented on include/utl/parser/csv.h
> +  while ((found_at = arg.find('"', found_at)) != -1) {
```suggestion
  while ((found_at = arg.find('"', found_at)) != std::string::npos) {
```

Not sure if it's defined to be `-1`.

2024-04-30 13:34 UTC, felixguendling commented on include/utl/parser/csv.h
> +      ++found_at;  // Skip following character
What if `found_at == arg.size() - 1`? Will it end in an infinite loop because you don't increment?

2024-05-02 07:30 UTC, felixguendling commented
Can you please add a test-case for the `found_at == s.size() - 1` case?

Somehow I don't get an email notification for force-push. So if you want me to have a look at it, it would help to request a new review or comment here. Or is there a way to subscribe to force-push events too?

2024-05-02 19:13 UTC, felixguendling approved these changes

2024-05-02 19:13 UTC, merged

2024-05-02 19:13 UTC, felixguendling commented
Thank you very much!